### ISSUE TITLE
bot error

### ISSUE THREAD

**Issue by Jacobenem** [FightRPG-DiscordBotRPG/FightRPG---Discord---BugTracker#2]
**Describe your issue.**  

**Error: Cannot enqueue Query after fatal error.
at (/home/admin/Discord-Bot-RPG-Discord/node_modules/mysql/lib/protocol/Protocol.js:200:16**

```js

< Error: Cannot enqueue Query after fatal error.
at (/home/admin/Discord-Bot-RPG-Discord/node_modules/mysql/lib/protocol/Protocol.js:200:16>

```

** http://prntscr.com/niqavz **

**Comment by Roncarlos** [comment]
Fixed.
