### ISSUE TITLE
Bug ::talents

### ISSUE THREAD

**Issue by KhevenStark** [FightRPG-DiscordBotRPG/FightRPG---Discord---BugTracker#6]
**I just used ::talents and a error message appeared.**  

**Error: Request failed with status code 500
at (/var/fightrpg/DiscordBotRPG-Discord/node_modules/axios/lib/core/createError.js:16:15**

```js

< Error: Request failed with status code 500
at (/var/fightrpg/DiscordBotRPG-Discord/node_modules/axios/lib/core/createError.js:16:15>

```

** ![image](https://user-images.githubusercontent.com/91544796/135093762-dd11577f-b12f-4e82-a8af-aaa57c4f65ce.png) **

**Comment by Roncarlos** [comment]
Fixed. Due to Apache update.
